### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by shavy4452** [huyszn/coc-burntbase-cooldown-bypass#1]
Seems like burntbase  has changed it's authentication method. Can you update the repo?

**Comment by huyszn** [comment]
I just tried using the repo and it still works. Did you try logging out of burntbase and logging back in to get a new access token? It sounds like your access token has expired and the access token lasts one day.

**Comment by shavy4452** [comment]
Yea, I tried. The endpoint "Me" is removed as i saw. It is working well as checked thanks.
